services:
  bookshelf-ui:
    container_name: bookshelf_ui
    image: node:23.9.0-alpine3.21
    #por la ruta se pone asi
    volumes:
    - ../../..:/workspaces:cached
    #Para que no muera el contenedor
    command: sleep infinity
  #crear una red
    networks:
      - bookshelf

networks:
  bookshelf: